// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package zz

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type AddReactionParams struct {
	UserId   string `json:"user_id"`
	Reaction string `json:"reaction"`
}

type AddReactionStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func AddReaction(tx *sqlite.Conn) *AddReactionStmt {
	const querySQL = `
INSERT INTO reactions (user_id, reaction)
VALUES (?, ?)
    `

	ps := &AddReactionStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *AddReactionStmt) Run(
	params AddReactionParams,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, params.UserId)

	bindIndex++
	stmt.BindText(bindIndex, params.Reaction)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute addreaction SQL: %w", err)
	}

	return nil
}

func OnceAddReaction(
	tx *sqlite.Conn,
	params AddReactionParams,
) (
	err error,
) {
	ps := AddReaction(tx)

	return ps.Run(
		params,
	)
}
