// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package zz

import (
	"fmt"

	"zombiezen.com/go/sqlite"
)

type ReactionModel struct {
	Id        int64  `json:"id"`
	UserId    string `json:"user_id"`
	Reaction  string `json:"reaction"`
	Createdat *int64 `json:"createdat"`
}

type CreateReactionStmt struct {
	stmt *sqlite.Stmt
}

func CreateReaction(tx *sqlite.Conn) *CreateReactionStmt {
	stmt := tx.Prep(`
INSERT INTO reactions (
        id,
        user_id,
        reaction,
        createdat
) VALUES (
        ?,
        ?,
        ?,
        ?
)
    `)
	return &CreateReactionStmt{stmt: stmt}
}

func (ps *CreateReactionStmt) Run(m *ReactionModel) error {
	defer ps.stmt.Reset()

	// Bind parameters
	ps.stmt.BindInt64(1, m.Id)

	ps.stmt.BindText(2, m.UserId)

	ps.stmt.BindText(3, m.Reaction)

	if m.Createdat == nil {
		ps.stmt.BindNull(4)
	} else {
		ps.stmt.BindInt64(4, *m.Createdat)
	}

	if _, err := ps.stmt.Step(); err != nil {
		return fmt.Errorf("failed to insert reactions: %w", err)
	}

	return nil
}

func OnceCreateReaction(tx *sqlite.Conn, m *ReactionModel) error {
	ps := CreateReaction(tx)
	return ps.Run(m)
}

type UpsertReactionStmt struct {
	stmt *sqlite.Stmt
}

func UpsertReaction(tx *sqlite.Conn) *UpsertReactionStmt {
	stmt := tx.Prep(`
INSERT INTO reactions (
        id,
        user_id,
        reaction,
        createdat
) VALUES (
        ?,
        ?,
        ?,
        ?
)
ON CONFLICT(id) DO UPDATE SET
        user_id = excluded.user_id,
        reaction = excluded.reaction,
        createdat = excluded.createdat
    `)
	return &UpsertReactionStmt{stmt: stmt}
}

func (ps *UpsertReactionStmt) Run(m *ReactionModel) error {
	defer ps.stmt.Reset()

	// Bind parameters
	ps.stmt.BindInt64(1, m.Id)

	ps.stmt.BindText(2, m.UserId)

	ps.stmt.BindText(3, m.Reaction)

	if m.Createdat == nil {
		ps.stmt.BindNull(4)
	} else {
		ps.stmt.BindInt64(4, *m.Createdat)
	}

	if _, err := ps.stmt.Step(); err != nil {
		return fmt.Errorf("failed to upsert reactions: %w", err)
	}

	return nil
}

func OnceUpsertReaction(tx *sqlite.Conn, m *ReactionModel) error {
	ps := UpsertReaction(tx)
	return ps.Run(m)
}

type ReadAllReactionsStmt struct {
	stmt *sqlite.Stmt
}

func ReadAllReactions(tx *sqlite.Conn) *ReadAllReactionsStmt {
	stmt := tx.Prep(`
SELECT
        id,
        user_id,
        reaction,
        createdat
FROM reactions
    `)
	return &ReadAllReactionsStmt{stmt: stmt}
}

func (ps *ReadAllReactionsStmt) Run() ([]*ReactionModel, error) {
	defer ps.stmt.Reset()

	var models []*ReactionModel
	for {
		hasRow, err := ps.stmt.Step()
		if err != nil {
			return nil, fmt.Errorf("failed to read reactions: %w", err)
		} else if !hasRow {
			break
		}

		m := &ReactionModel{}

		m.Id = ps.stmt.ColumnInt64(0)

		m.UserId = ps.stmt.ColumnText(1)

		m.Reaction = ps.stmt.ColumnText(2)

		if ps.stmt.ColumnIsNull(3) {
			m.Createdat = nil
		} else {

			tmp := ps.stmt.ColumnInt64(3)

			m.Createdat = &tmp

		}

		models = append(models, m)
	}

	return models, nil
}

func OnceReadAllReactions(tx *sqlite.Conn) ([]*ReactionModel, error) {
	ps := ReadAllReactions(tx)
	return ps.Run()
}

type ReadByIDReactionStmt struct {
	stmt *sqlite.Stmt
}

func ReadByIDReaction(tx *sqlite.Conn) *ReadByIDReactionStmt {
	stmt := tx.Prep(`
SELECT
        id,
        user_id,
        reaction,
        createdat
FROM reactions
WHERE id = ?
    `)
	return &ReadByIDReactionStmt{stmt: stmt}
}

func (ps *ReadByIDReactionStmt) Run(id int64) (*ReactionModel, error) {
	defer ps.stmt.Reset()

	ps.stmt.BindInt64(1, id)

	if hasRow, err := ps.stmt.Step(); err != nil {
		return nil, fmt.Errorf("failed to read reactions: %w", err)
	} else if !hasRow {
		return nil, nil
	}

	m := &ReactionModel{}

	m.Id = ps.stmt.ColumnInt64(0)

	m.UserId = ps.stmt.ColumnText(1)

	m.Reaction = ps.stmt.ColumnText(2)

	if ps.stmt.ColumnIsNull(3) {
		m.Createdat = nil
	} else {

		tmp := ps.stmt.ColumnInt64(3)

		m.Createdat = &tmp

	}

	return m, nil
}

func OnceReadByIDReaction(tx *sqlite.Conn, id int64) (*ReactionModel, error) {
	ps := ReadByIDReaction(tx)
	return ps.Run(id)
}

func CountReactions(tx *sqlite.Conn) (int64, error) {
	stmt := tx.Prep(`
SELECT COUNT(*)
FROM reactions
    `)
	defer stmt.Reset()

	if hasRow, err := stmt.Step(); err != nil {
		return 0, fmt.Errorf("failed to count reactions: %w", err)
	} else if !hasRow {
		return 0, nil
	}

	return stmt.ColumnInt64(0), nil
}

func OnceCountReactions(tx *sqlite.Conn) (int64, error) {
	return CountReactions(tx)
}

type UpdateReactionStmt struct {
	stmt *sqlite.Stmt
}

func UpdateReaction(tx *sqlite.Conn) *UpdateReactionStmt {
	stmt := tx.Prep(`
UPDATE reactions
SET
        user_id = ?2,
        reaction = ?3,
        createdat = ?4
WHERE id = ?1
    `)
	return &UpdateReactionStmt{stmt: stmt}
}

func (ps *UpdateReactionStmt) Run(m *ReactionModel) error {
	defer ps.stmt.Reset()

	// Bind parameters
	ps.stmt.BindInt64(1, m.Id)

	ps.stmt.BindText(2, m.UserId)

	ps.stmt.BindText(3, m.Reaction)

	if m.Createdat == nil {
		ps.stmt.BindNull(4)
	} else {
		ps.stmt.BindInt64(4, *m.Createdat)
	}

	if _, err := ps.stmt.Step(); err != nil {
		return fmt.Errorf("failed to update reactions: %w", err)
	}

	return nil
}

func OnceUpdateReaction(tx *sqlite.Conn, m *ReactionModel) error {
	ps := UpdateReaction(tx)
	return ps.Run(m)
}

type DeleteReactionStmt struct {
	stmt *sqlite.Stmt
}

func DeleteReaction(tx *sqlite.Conn) *DeleteReactionStmt {
	stmt := tx.Prep(`
DELETE FROM reactions
WHERE id = ?
    `)
	return &DeleteReactionStmt{stmt: stmt}
}

func (ps *DeleteReactionStmt) Run(id int64) error {
	defer ps.stmt.Reset()

	ps.stmt.BindInt64(1, id)

	if _, err := ps.stmt.Step(); err != nil {
		return fmt.Errorf("failed to delete reactions: %w", err)
	}

	return nil
}

func OnceDeleteReaction(tx *sqlite.Conn, id int64) error {
	ps := DeleteReaction(tx)
	return ps.Run(id)
}
