// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package zz

import (
	"fmt"

	"zombiezen.com/go/sqlite"
)

type ReactionCountModel struct {
	Reaction string `json:"reaction"`
	Count    int64  `json:"count"`
}

type CreateReactionCountStmt struct {
	stmt *sqlite.Stmt
}

func CreateReactionCount(tx *sqlite.Conn) *CreateReactionCountStmt {
	stmt := tx.Prep(`
INSERT INTO reaction_counts (
        reaction,
        count
) VALUES (
        ?,
        ?
)
    `)
	return &CreateReactionCountStmt{stmt: stmt}
}

func (ps *CreateReactionCountStmt) Run(m *ReactionCountModel) error {
	defer ps.stmt.Reset()

	// Bind parameters
	ps.stmt.BindText(1, m.Reaction)

	ps.stmt.BindInt64(2, m.Count)

	if _, err := ps.stmt.Step(); err != nil {
		return fmt.Errorf("failed to insert reaction_counts: %w", err)
	}

	return nil
}

func OnceCreateReactionCount(tx *sqlite.Conn, m *ReactionCountModel) error {
	ps := CreateReactionCount(tx)
	return ps.Run(m)
}

type ReadAllReactionCountsStmt struct {
	stmt *sqlite.Stmt
}

func ReadAllReactionCounts(tx *sqlite.Conn) *ReadAllReactionCountsStmt {
	stmt := tx.Prep(`
SELECT
        reaction,
        count
FROM reaction_counts
    `)
	return &ReadAllReactionCountsStmt{stmt: stmt}
}

func (ps *ReadAllReactionCountsStmt) Run() ([]*ReactionCountModel, error) {
	defer ps.stmt.Reset()

	var models []*ReactionCountModel
	for {
		hasRow, err := ps.stmt.Step()
		if err != nil {
			return nil, fmt.Errorf("failed to read reaction_counts: %w", err)
		} else if !hasRow {
			break
		}

		m := &ReactionCountModel{}

		m.Reaction = ps.stmt.ColumnText(0)

		m.Count = ps.stmt.ColumnInt64(1)

		models = append(models, m)
	}

	return models, nil
}

func OnceReadAllReactionCounts(tx *sqlite.Conn) ([]*ReactionCountModel, error) {
	ps := ReadAllReactionCounts(tx)
	return ps.Run()
}

func CountReactionCounts(tx *sqlite.Conn) (int64, error) {
	stmt := tx.Prep(`
SELECT COUNT(*)
FROM reaction_counts
    `)
	defer stmt.Reset()

	if hasRow, err := stmt.Step(); err != nil {
		return 0, fmt.Errorf("failed to count reaction_counts: %w", err)
	} else if !hasRow {
		return 0, nil
	}

	return stmt.ColumnInt64(0), nil
}

func OnceCountReactionCounts(tx *sqlite.Conn) (int64, error) {
	return CountReactionCounts(tx)
}

type UpdateReactionCountStmt struct {
	stmt *sqlite.Stmt
}

func UpdateReactionCount(tx *sqlite.Conn) *UpdateReactionCountStmt {
	stmt := tx.Prep(`
UPDATE reaction_counts
SET
        count = ?2
WHERE id = ?1
    `)
	return &UpdateReactionCountStmt{stmt: stmt}
}

func (ps *UpdateReactionCountStmt) Run(m *ReactionCountModel) error {
	defer ps.stmt.Reset()

	// Bind parameters
	ps.stmt.BindText(1, m.Reaction)

	ps.stmt.BindInt64(2, m.Count)

	if _, err := ps.stmt.Step(); err != nil {
		return fmt.Errorf("failed to update reaction_counts: %w", err)
	}

	return nil
}

func OnceUpdateReactionCount(tx *sqlite.Conn, m *ReactionCountModel) error {
	ps := UpdateReactionCount(tx)
	return ps.Run(m)
}

type DeleteReactionCountStmt struct {
	stmt *sqlite.Stmt
}

func DeleteReactionCount(tx *sqlite.Conn) *DeleteReactionCountStmt {
	stmt := tx.Prep(`
DELETE FROM reaction_counts
WHERE id = ?
    `)
	return &DeleteReactionCountStmt{stmt: stmt}
}

func (ps *DeleteReactionCountStmt) Run(id int64) error {
	defer ps.stmt.Reset()

	ps.stmt.BindInt64(1, id)

	if _, err := ps.stmt.Step(); err != nil {
		return fmt.Errorf("failed to delete reaction_counts: %w", err)
	}

	return nil
}

func OnceDeleteReactionCount(tx *sqlite.Conn, id int64) error {
	ps := DeleteReactionCount(tx)
	return ps.Run(id)
}
