// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package zz

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type GetReactionCountsStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func GetReactionCounts(tx *sqlite.Conn) *GetReactionCountsStmt {
	const querySQL = `
SELECT reaction, count FROM reaction_counts ORDER BY count DESC
    `

	ps := &GetReactionCountsStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *GetReactionCountsStmt) Run() (
	res []*ReactionCountModel,
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	// Execute the query
	for {
		if hasRow, err := stmt.Step(); err != nil {
			return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
		} else if !hasRow {
			break
		}

		row := &ReactionCountModel{}
		row.Reaction = stmt.ColumnText(0)
		row.Count = stmt.ColumnInt64(1)
		res = append(res, row)
	}

	return res, nil
}

func OnceGetReactionCounts(
	tx *sqlite.Conn,
) (
	res []*ReactionCountModel,
	err error,
) {
	ps := GetReactionCounts(tx)

	return ps.Run()
}
