// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package zz

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type IncrementReactionCountStmt struct {
	conn      *sqlite.Conn
	stmt      *sqlite.Stmt
	querySQL  string
	hasSlices bool
}

func IncrementReactionCount(tx *sqlite.Conn) *IncrementReactionCountStmt {
	const querySQL = `
INSERT INTO reaction_counts (reaction, count)
VALUES (?, 1)
ON CONFLICT(reaction) DO UPDATE SET count = count + 1
    `

	ps := &IncrementReactionCountStmt{
		conn:      tx,
		querySQL:  querySQL,
		hasSlices: false,
	}

	if !ps.hasSlices {
		ps.stmt = tx.Prep(querySQL)
	}

	return ps
}

func (ps *IncrementReactionCountStmt) Run(
	reaction string,
) (
	err error,
) {
	querySQL := ps.querySQL

	var stmt *sqlite.Stmt
	if ps.hasSlices {
		stmt = ps.conn.Prep(querySQL)
	} else {
		stmt = ps.stmt
	}

	defer func() {
		_ = stmt.ClearBindings()
		_ = stmt.Reset()
	}()

	bindIndex := 1
	// Bind parameters
	stmt.BindText(bindIndex, reaction)

	bindIndex++

	// Execute the query
	if _, err := stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute incrementreactioncount SQL: %w", err)
	}

	return nil
}

func OnceIncrementReactionCount(
	tx *sqlite.Conn,
	reaction string,
) (
	err error,
) {
	ps := IncrementReactionCount(tx)

	return ps.Run(
		reaction,
	)
}
